# This is a basic workflow to help you get started with Actions

name: Push updates on branch v2 to public repo

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches:
      - v2

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  copy-file:
    runs-on: ubuntu-latest
    env: 
       
       # these env vars are set using action
       CURR_BRANCH: 'v2'
       DEST_REPO: 'redbayoub/portfolio-v2'
  
       COMMIT_MESSAGE: 'push updates from private'
       COMMIT_USERNAME: 'github-bot'
       COMMIT_EMAIL: 'github-bot@example.com'
       SOURCE_REPO_PATH: './source_repo'
       DEST_REPO_PATH: './dest_repo'
     
    steps:
    
    - name: Checkout code the current repo with the current branch
      uses: actions/checkout@v2
      with:
        path:  ${{ env.SOURCE_REPO_PATH }}
   
    - name: clone dest repo
      run: git clone "https://github.com/$DEST_REPO.git" "$DEST_REPO_PATH"
      
    - name: set commit email & username
      run: |
       git config --global user.email "$COMMIT_EMAIL"
       git config --global user.name "$COMMIT_USERNAME"

    
    - name: copy files
      run: cp -a -r "$SOURCE_REPO_PATH" "$DEST_REPO_PATH"
    
    - name: add all files to git & commit & push
      run: |
        cd "$DEST_REPO_PATH"
        git add .
        git commit --message "$COMMIT_MESSAGE"
        git push -u origin
