# This is a basic workflow to help you get started with Actions

name: Push updates on branch v2 to public repo

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches:
      - v2

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  copy-file:
    runs-on: ubuntu-latest
    env: 
       DEST_REPO: 'redbayoub/portfolio-v2' 
  
       COMMIT_MESSAGE: 'updates portfolio-v2'
       COMMIT_USERNAME: 'github-bot'
       COMMIT_EMAIL: 'github-bot@example.com'
     
    steps:
    - name: Checkout
      uses: actions/checkout@v2 
      
    - name: Push a folder to another repository
      uses: crykn/copy_folder_to_another_repo_action@v1.0.6
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with: 
        source_folder: "."
        destination_repo: ${{ env.DEST_REPO }}
        user_email:  ${{ env.COMMIT_EMAIL }}
        user_name:  ${{ env.COMMIT_USERNAME }}
        commit_msg:  ${{ env.COMMIT_MESSAGE }}
 
