# This is a basic workflow to help you get started with Actions

name: Push updates on branch v2 to public repo

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches:
      - v2

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  copy-file:
    runs-on: ubuntu-latest
    env: 
       DEST_REPO: 'redbayoub/portfolio-v2' 
     
    steps:
    - name: Checkout
      uses: actions/checkout@v2 
      
    - name: add the dest repo
      run: git remote add origin2 "https://github.com/$DEST_REPO.git"
    
    - name: push updates
      run: git push origin2 v2

 
